### ISSUE TITLE
bandwidth

### ISSUE THREAD

**Issue by EnoSat** [Duckbox-Developers/dvbsnoop#1]
-Hi, what not work bandwidth ?
root@osmio4kplus:~# dvbsnoop -s bandwidth
dvbsnoop  - a dvb/mpeg2 stream analyzer tool
Version: 1.4.56/api-3  (Oct 29 2020 12:39:00)
         https://github.com/OpenVisionE2/dvbsnoop
         (c) 2001-2007  Rainer Scherg  (rasc)

This is a modified version of dvbsnoop, see https://github.com/Duckbox-Developers/dvbsnoop for more info.

For help type 'dvbsnoop -help' ...

**Comment by BPanther** [comment]
Please read the doc, parameters are missing, e.g.

dvbsnoop -s bandwidth -n 3000 -pd 3  0xa6

You find the same with G here: http://dvbsnoop.sourceforge.net/examples/example-bandwidth.html


Example for RBB Berlin (SD):
dvbsnoop -s bandwidth -n 3000 -pd 3 0x14bf
dvbsnoop V1.4.5X -- http://dvbsnoop.sourceforge.net/

---------------------------------------------------------
PID bandwidth statistics...
PID: 5311 (0x14bf)   - max packet count: 3000
---------------------------------------------------------
packets read: 2048/(2048)   d_time:  0.241 s  = 12780.880 kbit/s   (Avrg: 12780.880 kbit/s)
packets read:   1/(2049)   d_time:  0.001 s  =  1504.000 kbit/s   (Avrg: 12787.120 kbit/s)
packets read: 2048/(4097)   d_time:  0.222 s  = 13874.739 kbit/s   (Avrg: 13308.613 kbit/s)
PID: 5311 (0x14bf)
